### ISSUE TITLE
Crash when using the woodcutter on Dynamic Trees

### ISSUE THREAD

**Issue by RypoFalem** [dalapo/FactoryTech#39]
```
Description: Ticking block entity

java.lang.ClassCastException: com.ferreusveritas.dynamictrees.blocks.BlockBranch cannot be cast to net.minecraft.block.BlockLog
	at dalapo.factech.tileentity.specialized.TileEntityWoodcutter.performAction(TileEntityWoodcutter.java:63)
	at dalapo.factech.tileentity.TileEntityMachine.func_73660_a(TileEntityMachine.java:207)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)
```
[full crash report](https://hastebin.com/elivavoqer.txt)

https://github.com/dalapo/FactoryTech/blob/a581449b69b27f7c4f4541ac88259f68aeaf838c/src/main/java/dalapo/factech/tileentity/specialized/TileEntityWoodcutter.java#L63

Dynamic Trees branches (what they use instead of logs) return true for isWood() but don't extend BlockLog.

**Comment by dalapo** [comment]
Should be fixed now - I removed the need to cast to BlockLog. Gonna keep this issue open since the next version isn't released yet.

**Comment by xenoflot** [comment]
May be the same bug. https://gist.github.com/xenoflot/0942ef99656b3bf979007e3aa125583f

Tried growing a Forestry Coast Sequoia in front of a Woodcutter. Client froze :(
