### ISSUE TITLE
Pipe Randomly Causing A Crash

### ISSUE THREAD

**Issue by EmosewaGamer** [dalapo/FactoryTech#44]
So a Pipe was transferring Actually Additions Canola Oil to an Oil Generator. Everything was working fine, but after an hour the pipe caused a world crash as a ticking tile entity: https://pastebin.com/UCZhsL81

**Comment by dalapo** [comment]
That's an AA bug, not mine. I've created a pull request for it, but until then there's not much I can do unfortunately.

**Comment by EmosewaGamer** [comment]
Ah, ok. I figured since AA was mentioned first on the crash log.

**Comment by dalapo** [comment]
AA just merged the request, so it should be fixed whenever it updates next.

**Comment by kitsu** [comment]
I may be having the same crash. It is hard to track because it usually hangs Minecraft instead of crashing.
My setup is an Astral Sorcery Light Well producing liquid starlight, add some FT pipes connected to Tinker's seared gauge (tanks), and it reliably fails/crashes when I connect a FT pump between the bottom of the Light Well and the pipes.

```
W      W: Well (Add crystal to start generating starlight)
V      V: Pump
|-T    |-: Pipe
|-T    T: Tank
```

```
[20:00:03] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:771) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:50) ~[FluidStack.class:?]
	at dalapo.factech.tileentity.automation.TileEntityPipe.propagateFluid(TileEntityPipe.java:105) ~[TileEntityPipe.class:?]
	at dalapo.factech.tileentity.automation.TileEntityPipe.func_73660_a(TileEntityPipe.java:152) ~[TileEntityPipe.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1832) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765) ~[MinecraftServer.class:?]
	... 4 more
[20:00:07] [Server thread/ERROR]: This crash report has been saved to: C:\MultiMC\instances\1.12.2-Industry\minecraft\crash-reports\crash-2018-01-30_20.00.06-server.txt
```

Let me know if it is an Astral Sorcery bug and I'll go report it there.
